/*

 FRONT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\danirod\Desktop\GameBoy\game\res\intro.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __front_h_INCLUDE
#define __front_h_INCLUDE

#define frontWidth 20
#define frontHeight 18
#define frontBank 0

#define front frontPLN0
extern const unsigned char frontPLN0[];

#endif

/* End of FRONT.H */
