/*

 MAP_INTRO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : pal_intro.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map_intro_h_INCLUDE
#define __map_intro_h_INCLUDE

#define map_introWidth 20
#define map_introHeight 18
#define map_introBank 0

#define map_intro map_introPLN0
extern const unsigned char map_introPLN0[];

#endif

/* End of MAP_INTRO.H */
