/*

 MAP_GAME.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : pal_game.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __map_game_h_INCLUDE
#define __map_game_h_INCLUDE

#define map_gameWidth 20
#define map_gameHeight 18
#define map_gameBank 0

#define map_game map_gamePLN0
extern const unsigned char map_gamePLN0[];

#endif

/* End of MAP_GAME.H */
