/*

 PAL_CURSOR.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 7

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __pal_cursor_h_INCLUDE
#define __pal_cursor_h_INCLUDE

/* Bank of tiles. */
#define pal_cursorBank 0
/* Start of tile array. */
extern const unsigned char pal_cursor[];
#define pal_cursorLen 8

#endif

/* End of PAL_CURSOR.H */
