/*

 PAL_INTRO.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 191

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __pal_intro_h_INCLUDE
#define __pal_intro_h_INCLUDE

/* Bank of tiles. */
#define pal_introBank 0

/* Super Gameboy palette 0 */
#define pal_introSGBPal0c0 0
#define pal_introSGBPal0c1 0
#define pal_introSGBPal0c2 0
#define pal_introSGBPal0c3 0

/* Super Gameboy palette 1 */
#define pal_introSGBPal1c0 6076
#define pal_introSGBPal1c1 8935
#define pal_introSGBPal1c2 6596
#define pal_introSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define pal_introSGBPal2c0 6076
#define pal_introSGBPal2c1 8935
#define pal_introSGBPal2c2 6596
#define pal_introSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define pal_introSGBPal3c0 6076
#define pal_introSGBPal3c1 8935
#define pal_introSGBPal3c2 6596
#define pal_introSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define pal_introCGBPal0c0 32767
#define pal_introCGBPal0c1 21140
#define pal_introCGBPal0c2 9513
#define pal_introCGBPal0c3 0

/* Gameboy Color palette 1 */
#define pal_introCGBPal1c0 6076
#define pal_introCGBPal1c1 8935
#define pal_introCGBPal1c2 6596
#define pal_introCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define pal_introCGBPal2c0 6076
#define pal_introCGBPal2c1 8935
#define pal_introCGBPal2c2 6596
#define pal_introCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define pal_introCGBPal3c0 6076
#define pal_introCGBPal3c1 8935
#define pal_introCGBPal3c2 6596
#define pal_introCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define pal_introCGBPal4c0 6076
#define pal_introCGBPal4c1 8935
#define pal_introCGBPal4c2 6596
#define pal_introCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define pal_introCGBPal5c0 6076
#define pal_introCGBPal5c1 8935
#define pal_introCGBPal5c2 6596
#define pal_introCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define pal_introCGBPal6c0 6076
#define pal_introCGBPal6c1 8935
#define pal_introCGBPal6c2 6596
#define pal_introCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define pal_introCGBPal7c0 6076
#define pal_introCGBPal7c1 8935
#define pal_introCGBPal7c2 6596
#define pal_introCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char pal_intro[];
#define pal_introLen 192

#endif

/* End of PAL_INTRO.H */
