/*

 SWEEPER_BACK.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : sweeper.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __sweeper_back_h_INCLUDE
#define __sweeper_back_h_INCLUDE

#define sweeper_backendWidth 20
#define sweeper_backendHeight 18
#define sweeper_backendBank 0

#define sweeper_backend sweeper_backendPLN0
extern const unsigned char sweeper_backendPLN0[];

#endif

/* End of SWEEPER_BACK.H */
