/*

 SWEEPER_FRONT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\danirod\Desktop\GameBoy\game\res\sweeper.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __sweeper_front_h_INCLUDE
#define __sweeper_front_h_INCLUDE

#define sweeper_frontWidth 20
#define sweeper_frontHeight 18
#define sweeper_frontBank 0

#define sweeper_front sweeper_frontPLN0
extern const unsigned char sweeper_frontPLN0[];

#endif

/* End of SWEEPER_FRONT.H */
