/*

 SWEEPER_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 34

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __sweeper_tiles_h_INCLUDE
#define __sweeper_tiles_h_INCLUDE

/* Bank of tiles. */
#define sweeper_tilesBank 0
/* Start of tile array. */
extern const unsigned char sweeper_tiles[];

#endif

/* End of SWEEPER_TILES.H */
