/*

 TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 16 x 16
  Tiles                : 0 to 4

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tiles_h_INCLUDE
#define __tiles_h_INCLUDE

/* Bank of tiles. */
#define sweeper_spritesBank 0
/* Start of tile array. */
extern const unsigned char sweeper_sprites[];
#define sweeper_spritesLen 5

#endif

/* End of TILES.H */
